### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Infinitay** [Joxroxagain/adidas-bruteforcer#1]
Looking thru the code, it seems like you have created this based on KJU (https://github.com/bequadro/kju).

Do you have any plans on adding proxy support?

**Comment by Joxroxagain** [comment]
I actually just found out about KJU and yes I did use some of that code to get this up and running quickly. To answer your question, yes I will add proxy support today!

**Comment by Joxroxagain** [comment]
@Infinitay message me on discord @ SoFloJoe#4498 if you are interested in contributing!
